### ISSUE TITLE
(enhancement) share colours with editor

### ISSUE THREAD

**Issue by stagfoo** [StevenIseki/ld-color-picker#2]
it would be nice if we could find a way to have only color.js for colors in the color picker and editor because for now if color.js(editor) != color.js(ld-color-picker) you will get no/wrong colors because of how draft works.

inside the plugin system is there a way access the styleMap? if so we could pull out the colors there and generator what is need for the color picker.

**Comment by stagfoo** [comment]
Or pass in the same colours to both?

**Comment by svnm** [comment]
@stagfoo This sounds like a good idea, I wanted to keep plugins fairly isolated so don't want them to have access to the stylemap. But probably the best idea is to publish a simple module, maybe `ld-colors` which just exports all of the colors, then Last Draft and ld-color-picker just has to use the same version.

**Comment by svnm** [comment]
@stagfoo This is all working now in `last-draft` v1.2.6, using `ld-color-picker` v1.0.3. Thanks for the awesome work 🚀
